import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import Products from './Products';
import * as endpoints from '../api/generated/endpoints';

// Mock the API hooks generated by Orval
vi.mock('../api/generated/endpoints', () => ({
    useGetProducts: vi.fn(),
    usePostProducts: vi.fn(() => ({ mutate: vi.fn(), isPending: false }))
}));

describe('Products Page', () => {
    const queryClient = new QueryClient();

    it('renders products page correctly with fetched data', () => {
        // Setup the mock return value for our hook
        vi.mocked(endpoints.useGetProducts).mockReturnValue({
            data: { data: [{ id: '1', name: 'Awesome Product', price: 99.99, category: 'Tech', description: 'A great product' }] },
            isLoading: false,
            error: null,
        } as any);

        render(
            <QueryClientProvider client={queryClient}>
                <Products />
            </QueryClientProvider>
        );

        expect(screen.getByText('Products')).toBeInTheDocument();
        expect(screen.getByTestId('add-product-button')).toBeInTheDocument();
        expect(screen.getByText('Awesome Product')).toBeInTheDocument();
    });
});